### ISSUE TITLE
Failed to build delorean

### ISSUE THREAD

**Issue by ddeimeke** [artur-shaik/wallabag-client#6]
I try to build wallabag on Ubuntu 20.04.1 with Python 3.8.5 and pip 20.0.2

After setting up the virtualenv (wheel is installed), I get the following error:

```
...
Building wheels for collected packages: delorean
  Building wheel for delorean (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dirk/venv/wallabag-client/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b7j6ynf0/delorean/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b7j6ynf0/delorean/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yot5_9f3
       cwd: /tmp/pip-install-b7j6ynf0/delorean/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for delorean
  Running setup.py clean for delorean
Failed to build delorean
...
```

**Comment by artur-shaik** [comment]
Hello. Looks like something with your setup. Are you sure you have `wheel` for python __3__ and not legacy version 2?

**Comment by ddeimeke** [comment]
No, I only have python3-wheel on my system.

```
$ dpkg -l | grep -i wheel
ii  python3-wheel                              0.34.2-1                              all          built-package format for Python
```

**Comment by artur-shaik** [comment]
Can you show your sequence of actions, please?

**Comment by ddeimeke** [comment]
Yes, sure:

```
dirk@crest:~$ python3 -m venv ~/venv/wallabag-client
```

```
dirk@crest:~$ source ~/venv/wallabag-client/bin/activate
```

```
(wallabag-client) dirk@crest:~$ pip3 install wallabag-client
Collecting wallabag-client
  Using cached wallabag_client-1.6.2-py3-none-any.whl (37 kB)
Collecting colorama>=0.4.3
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pyxdg
  Using cached pyxdg-0.27-py2.py3-none-any.whl (49 kB)
Collecting requests>=2.11.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting click<8.0,>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting tzlocal<3
  Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting tabulate
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting pycryptodome>=3.9.8
  Using cached pycryptodome-3.9.9-cp38-cp38-manylinux1_x86_64.whl (13.7 MB)
Collecting click-repl>=0.1.6
  Using cached click_repl-0.1.6-py3-none-any.whl (4.2 kB)
Collecting delorean
  Using cached Delorean-1.0.0.tar.gz (18 kB)
Collecting lxml
  Using cached lxml-4.6.2-cp38-cp38-manylinux1_x86_64.whl (5.4 MB)
Collecting humanize
  Using cached humanize-3.2.0-py3-none-any.whl (70 kB)
Collecting beautifulsoup4>=4.9.1
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting click-spinner
  Using cached click_spinner-0.1.10-py2.py3-none-any.whl (4.0 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting pytz
  Using cached pytz-2020.5-py2.py3-none-any.whl (510 kB)
Collecting prompt-toolkit
  Using cached prompt_toolkit-3.0.8-py3-none-any.whl (355 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting babel>=2.1.1
  Using cached Babel-2.9.0-py2.py3-none-any.whl (8.8 MB)
Collecting python-dateutil>=2.4.2
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: setuptools in ./venv/wallabag-client/lib/python3.8/site-packages (from humanize->wallabag-client) (44.0.0)
Collecting soupsieve>1.2; python_version >= "3.0"
  Using cached soupsieve-2.1-py3-none-any.whl (32 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Building wheels for collected packages: delorean
  Building wheel for delorean (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dirk/venv/wallabag-client/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m3pkgnf6/delorean/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m3pkgnf6/delorean/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vdct0xn3
       cwd: /tmp/pip-install-m3pkgnf6/delorean/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for delorean
  Running setup.py clean for delorean
Failed to build delorean
Installing collected packages: colorama, pyxdg, urllib3, idna, chardet, certifi, requests, click, pytz, tzlocal, tabulate, pycryptodome, wcwidth, prompt-toolkit, six, click-repl, babel, humanize, python-dateutil, delorean, lxml, soupsieve, beautifulsoup4, click-spinner, wallabag-client
    Running setup.py install for delorean ... done
Successfully installed babel-2.9.0 beautifulsoup4-4.9.3 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 click-repl-0.1.6 click-spinner-0.1.10 colorama-0.4.4 delorean-1.0.0 humanize-3.2.0 idna-2.10 lxml-4.6.2 prompt-toolkit-3.0.8 pycryptodome-3.9.9 python-dateutil-2.8.1 pytz-2020.5 pyxdg-0.27 requests-2.25.1 six-1.15.0 soupsieve-2.1 tabulate-0.8.7 tzlocal-2.1 urllib3-1.26.2 wallabag-client-1.6.2 wcwidth-0.2.5
```

**Comment by artur-shaik** [comment]
Can you try to make setup from sources `pip install ~/wallabag-source-path/` using this branch: https://github.com/artur-shaik/wallabag-client/tree/try-with-wheel ?

**Comment by ddeimeke** [comment]
Does not work either.

**Comment by artur-shaik** [comment]
Same errors?

**Comment by ddeimeke** [comment]
Yes.

I clicked a Digital Ocean droplet with Ubuntu 20.04 and installed all updates.

After that I installed

```
# apt install python3-pip python3-setuptools python3-wheel python3-venv
```

And I still get the same error.

**Comment by ddeimeke** [comment]
Strange enough, you additionally need to install wheel via pip.
```

[dirk@crest:~] [wallabag-client] $ pip3 install wheel
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
[dirk@crest:~] [wallabag-client] $ pip3 install wallabag-client
Collecting wallabag-client
  Using cached wallabag_client-1.6.2-py3-none-any.whl (37 kB)
Collecting click-repl>=0.1.6
  Using cached click_repl-0.1.6-py3-none-any.whl (4.2 kB)
Collecting requests>=2.11.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting click-spinner
  Using cached click_spinner-0.1.10-py2.py3-none-any.whl (4.0 kB)
Collecting humanize
  Using cached humanize-3.2.0-py3-none-any.whl (70 kB)
Collecting tabulate
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting colorama>=0.4.3
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting delorean
  Using cached Delorean-1.0.0.tar.gz (18 kB)
Collecting pyxdg
  Using cached pyxdg-0.27-py2.py3-none-any.whl (49 kB)
Collecting click<8.0,>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting pycryptodome>=3.9.8
  Using cached pycryptodome-3.9.9-cp38-cp38-manylinux1_x86_64.whl (13.7 MB)
Collecting beautifulsoup4>=4.9.1
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting lxml
  Using cached lxml-4.6.2-cp38-cp38-manylinux1_x86_64.whl (5.4 MB)
Collecting tzlocal<3
  Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting prompt-toolkit
  Using cached prompt_toolkit-3.0.8-py3-none-any.whl (355 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: setuptools in ./venv/wallabag-client/lib/python3.8/site-packages (from humanize->wallabag-client) (44.0.0)
Collecting babel>=2.1.1
  Using cached Babel-2.9.0-py2.py3-none-any.whl (8.8 MB)
Collecting python-dateutil>=2.4.2
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2015.7
  Using cached pytz-2020.5-py2.py3-none-any.whl (510 kB)
Collecting soupsieve>1.2; python_version >= "3.0"
  Using cached soupsieve-2.1-py3-none-any.whl (32 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Building wheels for collected packages: delorean
  Building wheel for delorean (setup.py) ... done
  Created wheel for delorean: filename=Delorean-1.0.0-py3-none-any.whl size=9580 sha256=9cd90da586be452552bac840682a98a7f0a56fde125e1c41aedfe1f5e9922392
  Stored in directory: /home/dirk/.cache/pip/wheels/49/77/4b/f7473beb109479697917a0b8e8c79cebee448820d9bd7aecd6
Successfully built delorean
Installing collected packages: click, wcwidth, prompt-toolkit, six, click-repl, certifi, chardet, urllib3, idna, requests, click-spinner, humanize, tabulate, colorama, pytz, babel, python-dateutil, tzlocal, delorean, pyxdg, pycryptodome, soupsieve, beautifulsoup4, lxml, wallabag-client
Successfully installed babel-2.9.0 beautifulsoup4-4.9.3 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 click-repl-0.1.6 click-spinner-0.1.10 colorama-0.4.4 delorean-1.0.0 humanize-3.2.0 idna-2.10 lxml-4.6.2 prompt-toolkit-3.0.8 pycryptodome-3.9.9 python-dateutil-2.8.1 pytz-2020.5 pyxdg-0.27 requests-2.25.1 six-1.15.0 soupsieve-2.1 tabulate-0.8.7 tzlocal-2.1 urllib3-1.26.2 wallabag-client-1.6.2 wcwidth-0.2.5
[dirk@crest:~] [wallabag-client] 7s $ wallabag 
Traceback (most recent call last):
  File "/home/dirk/venv/wallabag-client/bin/wallabag", line 5, in <module>
    from wallabag.wallabag import cli
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/wallabag.py", line 15, in <module>
    from wallabag.commands.add import AddCommand, AddCommandParams
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/commands/add.py", line 5, in <module>
    from wallabag.api.add_entry import AddEntry, Params as AddEntryParams
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/api/add_entry.py", line 5, in <module>
    from wallabag.api.api import Api, ApiMethod, ValueException
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/api/api.py", line 11, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by ddeimeke** [comment]
Shall I create an additional issue for the `ModuleNotFoundError: No module named 'packaging'`?

**Comment by ddeimeke** [comment]
Any objections adding this to setup.py?

```
setup(
    ...
    setup_requires=['wheel']
)
```

**Comment by artur-shaik** [comment]
> Any objections adding this to setup.py?
> 
> ```
> setup(
>     ...
>     setup_requires=['wheel']
> )
> ```

I, actually, did this in new branch.

**Comment by artur-shaik** [comment]
> Shall I create an additional issue for the `ModuleNotFoundError: No module named 'packaging'`?

I will add it to `install_requires`.

**Comment by artur-shaik** [comment]
Just released new minor version, can you try it?

**Comment by ddeimeke** [comment]
@artur-shaik 

Thanks for your support.

Installation works perfectly well. Start works as well. I will do some testing and open new issues if necessary.
