### ISSUE TITLE
local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by disasterism** [artur-shaik/wallabag-client#8]
When running the list command I get the following output.
```
Traceback (most recent call last):
  File "/usr/bin/wallabag", line 33, in <module>
    sys.exit(load_entry_point('wallabag-client==1.6.3', 'console_scripts', 'wallabag')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/wallabag/wallabag.py", line 93, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/wallabag/wallabag.py", line 128, in list
    run_command(
  File "/usr/lib/python3.9/site-packages/wallabag/wallabag.py", line 472, in run_command
    result, output = command.execute()
  File "/usr/lib/python3.9/site-packages/wallabag/commands/command.py", line 22, in execute
    return self._run()
  File "/usr/lib/python3.9/site-packages/wallabag/commands/list.py", line 59, in _run
    api.request().response['_embedded']["items"])
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 200, in request
    return self._make_request(request)
  File "/usr/lib/python3.9/site-packages/wallabag/api/get_list_entries.py", line 41, in _make_request
    return self._request_get(request)
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 230, in _request_get
    return self.__make_request(request)
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 325, in __make_request
    response = Response(
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 146, in __init__
    f"An unknown error occured. {result.status_code}",
UnboundLocalError: local variable 'result' referenced before assignment
```

I suspect, from my limited understanding, I am supposed to be getting just the unknown error message rather than the python trace. Although it would be helpful to know why I get that error as well.

**Comment by disasterism** [comment]
Not sure if this is helpful but I get a somewhat similar output from the add command. although it is worth noting that despite the error the add command is successful. 

```
Traceback (most recent call last):
  File "/usr/bin/wallabag", line 33, in <module>
    sys.exit(load_entry_point('wallabag-client==1.6.3', 'console_scripts', 'wallabag')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/wallabag/wallabag.py", line 93, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/wallabag/wallabag.py", line 217, in add
    run_command(AddCommand(ctx.obj, params), quiet)
  File "/usr/lib/python3.9/site-packages/wallabag/wallabag.py", line 472, in run_command
    result, output = command.execute()
  File "/usr/lib/python3.9/site-packages/wallabag/commands/command.py", line 22, in execute
    return self._run()
  File "/usr/lib/python3.9/site-packages/wallabag/commands/add.py", line 45, in _run
    entry = Entry(AddEntry(self.config, params.target_url, {
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 200, in request
    return self._make_request(request)
  File "/usr/lib/python3.9/site-packages/wallabag/api/add_entry.py", line 32, in _make_request
    return self._request_post(request)
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 234, in _request_post
    return self.__make_request(request)
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 325, in __make_request
    response = Response(
  File "/usr/lib/python3.9/site-packages/wallabag/api/api.py", line 146, in __init__
    f"An unknown error occured. {result.status_code}",
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by artur-shaik** [comment]
Yeah,  can confim this is bug. Will fix it later. Thank you very much.
