### ISSUE TITLE
--count does not work for me

### ISSUE THREAD

**Issue by ddeimeke** [artur-shaik/wallabag-client#9]
Can you please have a look - wallabag-client 1.6.4 on Ubuntu 20.04, installed via pip.

```
$ wallabag list --unread --count
Traceback (most recent call last):
  File "/home/dirk/venv/wallabag-client/bin/wallabag", line 8, in <module>
    sys.exit(cli())
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/wallabag.py", line 93, in wrapper
    func(*args, **kwargs)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/wallabag.py", line 128, in list
    run_command(
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/wallabag.py", line 472, in run_command
    result, output = command.execute()
  File "/home/dirk/venv/wallabag-client/lib/python3.8/site-packages/wallabag/commands/command.py", line 16, in execute
    self.log.debug('executing command: %s', self.__class__.__name__)
AttributeError: 'CountCommand' object has no attribute 'log'

```

**Comment by artur-shaik** [comment]
It's a bug, thank you.

**Comment by ddeimeke** [comment]
Thank you.
